### ISSUE TITLE
server can not handle old client side requests

### ISSUE THREAD

**Issue by golya** [keymandll/FuzzLabs#13] opened 2015-09-30 08:59 UTC
If you have an old instance on client side but the server is restarted then the server can not handle the old periodically sent client side requests.

**Comment by keymandll** [comment] 2015-09-30 16:46
I could not reproduce this.
I did the following:
 1. Started the web server
 2. Registered a user
 3. Logged in
 4. Added a new engine, basically just as an indicator and to test later
 5. Stopped webserver
 6. Waited 1-2 seconds and started the web server again

Everything was working perfectly fine. Just to make sure, I attempted to delete the engine I have created before restarting the server. The engine was deleted without any problem. Could not see any error message anywhere either.

Any idea on how I could reproduce?

**Comment by golya** [comment] 2015-10-01 17:54
I think the key was at my case that my session probably expired. Do you think it could be the cause?

**Comment by keymandll** [comment] 2015-10-03 09:08
There is really no session timeout at the moment. Anyway, as we agreed earlier we will ignore this as:
 - this issue is unlikely to manifest during normal operation
 - we could not reproduce it
 - the issue itself is nothing more than an exception and does not result in a fail
According to the above, I will close this issue. Once we can reproduce it we can open a new issue for it.

**Closed by keymandll** 2015-10-03 09:08 UTC
